### ISSUE TITLE
如何生成epub

### ISSUE THREAD

**Issue by cyejing** [MeouSker77/ProgrammingRust#16]
如何生成epub，或者release也生成epub文本，谢谢

**Comment by MeouSker77** [comment]
latex本身是不支持生成epub的，有一些别的工具可以从.tex文件生成epub，比如pandoc，你可以自己试试，我没转过epub所以没用过

**Comment by cyejing** [comment]
`pandoc main.tex -o main.epub`
可以生成epub， 但需要处理一下’ch03.tex‘ 文件的一处报错
