### ISSUE TITLE
第三章-基本类型章-Checked、Wrapping、Saturating、Overflowing算术节-Saturating 翻译有误

### ISSUE THREAD

**Issue by Biubiubiubiujiu** [MeouSker77/ProgrammingRust#34]
第三章-基本类型章-Checked、Wrapping、Saturating、Overflowing算术节

Saturating 部分的翻译：“overflowing_shl和overflowing_shr稍微有些偏离这个模式：只有当移位距离**恰好等于**类型的位宽度时overflowed才为true。”

原文为：overflowing_shl and overflowing_shr deviate from the pattern a bit: they return true for overflowed only if the shift distance was **as large or larger than** the bit width of the type itself.

这里应该是“**大于等于**类型的位宽度时overflowed才为true。”

**Comment by MeouSker77** [comment]
感谢指正，已修复
